export const icons = {
  notifications: 'bell-outline',
  profile: 'account-circle-outline',
  wifi: 'wifi',
  batteryLow: 'battery-20',
  schedule: 'clock-outline',
  pill: 'pill',
  medication: 'pill',
  inventory: 'package-variant-closed',
  more: 'dots-vertical',
  filter: 'filter-variant',
  search: 'magnify',
  settings: 'cog-outline',
  diagnostics: 'stethoscope',
  motor: 'cog-transfer-outline',
  warning: 'alert-outline',
  visibilityOff: 'eye-off-outline',
  speaker: 'volume-high',
  rtc: 'clock-check-outline',
  ir: 'access-point',
  empty: 'tray-alert',
  loading: 'progress-clock',
  chevronRight: 'chevron-right',
} as const;

export type AppIcon = keyof typeof icons;
